export { default as useProducts } from "./hooks/useProducts"
export { ProductGallery } from "./components/ProductGallery"
export { ProductInfo } from "./components/ProductInfo"
export { RelatedProducts } from "./components/RelatedProducts"
export { useProductBySlug } from "./hooks/useProductBySlug"
export { getRelatedProducts } from "./utils/getRelatedProducts"